name: Python Tests (Fast)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: [self-hosted, Linux, X64, gpu]
    container:
      image: nvidia/cuda:11.8.0-devel-ubuntu20.04
      options: --gpus all
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.19.x'
      - name: Setup ccache
        run: |
          apt update && apt install -y ccache
      - name: Build hidet
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          bash scripts/build_wheel.sh
          WHEEL=$(find ./scripts/ -maxdepth 1 -name '*.whl')
          echo "Built wheel: $WHEEL" 
          pip install --no-deps --force-reinstall $WHEEL
      - name: Run minimal tests
        run: |
          python -m pytest -v tests/minimal/test_add.py
      - name: Run full tests
        run: |
          # stop the build if format is not correct
          python -m pytest -v ./tests
