name: Launch CI


on:
  workflow_dispatch:
    inputs:
      shutdown_instances:
        description: 'Shut down GPU instances when finished.'
        required: true
        type: boolean
        default: true
  issue_comment:
    types: [created]
  

jobs:
  trigger:
    if: |
      github.event_name == 'workflow_dispatch' || 
      github.event_name == 'issue_comment' && github.event.issue.pull_request != '' &&
      contains(fromJSON('["MEMBER", "OWNER", "COLLABORATOR"]'), github.event.comment.author_association) &&
      contains(github.event.comment.body, '$hidet-ci launch')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in internal repository
        run: |
         curl -L \
         -X POST \
         -H "Accept: application/vnd.github+json" \
         -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
         -H "X-GitHub-Api-Version: 2022-11-28" \
         https://api.github.com/repos/${{ secrets.REPO_NAME }}/actions/workflows/regression.yaml/dispatches \
         -d "{\"ref\": \"main\", \"inputs\": {\"shutdown_instances\": \"${{ env.SHUTDOWN }}\", \"source_repo\": \"${{ env.SOURCE_REPO }}\", \"source_ref\": \"${{ env.SOURCE_REF }}\"}}"
        env:
          SHUTDOWN: ${{ github.event_name == 'workflow_dispatch' && inputs.shutdown_instances || !contains(github.event.comment.body, '--keep') }}
          SOURCE_REPO: ${{ github.repository }}
          SOURCE_REF: ${{ github.event_name == 'workflow_dispatch' && github.ref_name || github.event.issue.number }}
