name: Publish to PyPI and Deploy Docs

permissions:
  contents: read

on:
  release:
    types: [published]

jobs:

  build-wheel:
    outputs:
      wheel_name: ${{ steps.build_step.outputs.wheel_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # we need the full history and tags for versioning
          fetch-tags: 'true'

      - name: Build Hidet Wheel
        id: build_step
        uses: ./.github/actions/build-wheel

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build_step.outputs.wheel_name }}
          path: ${{ steps.build_step.outputs.wheel_path }}
          retention-days: 1
          if-no-files-found: "error"

  list-test-dirs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:

      - name: Checkout Hidet
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - id: set-matrix
        run: |
          python .github/scripts/set_test_matrix.py

  run-tests:
    name: Release Tests
    needs: [list-test-dirs, build-wheel]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.list-test-dirs.outputs.matrix) }}
    runs-on: linux-amd64-gpu-l4-latest-1
    container:
      image: nvidia/cuda:12.6.2-devel-ubuntu22.04
    steps:
      - name: Install dependencies via apt
        run: |
          apt update && DEBIAN_FRONTEND=noninteractive apt install -y ccache git graphviz graphviz-dev

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-wheel.outputs.wheel_name }}

      - name: Setup Hidet from Wheel
        run: |
          pip install ${{ needs.build-wheel.outputs.wheel_name }}[dev]
  
      - name: List installed packages
        run: |
          pip list

      - name: Run tests
        run: |
          rm -rf ~/.config/hidet
          python -m pytest -v --durations=20 --clear-cache ${{ matrix.path }}

  build-docs:
    name: Build and Deploy Docs
    runs-on: linux-amd64-gpu-l4-latest-1
    container:
      image: us-east4-docker.pkg.dev/github-workflow-runners/hidet-base-ci/hidet-base-ci:latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build and deploy release docs
        uses: ./.github/actions/build-docs
        with:
          docs_deploy_token: ${{ secrets.WEBSITE_REPO_TOKEN }}
          update_docs: true

  publish:
    name: Publish to PyPI
    needs: [run-tests, build-docs, build-wheel]
    if: github.event_name == 'release' && github.event.action == 'published' && startsWith(github.event.release.tag_name, 'v')
    runs-on: ubuntu-latest
    steps:

      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-wheel.outputs.wheel_name }}

      - name: Show the wheel
        run: |
          ls -l
      
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: ./
